services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    networks:
    - inception
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
        - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
    - "443:443"
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/blarger/data/mariadb'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/blarger/data/wordpress'	

networks:
  inception:
    driver: bridge