services:
  mariadb:
    build:
      context: /sgoinfre/students/blarger/Inception/srcs/requirements/mariadb
      dockerfile: Dockerfile
    container_name: my-mariadb-container
    env_file: "maria.env"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
